# Generated by Django 2.0.5 on 2018-09-30 15:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50, verbose_name='Nome do Evento')),
                ('linkReference', models.URLField(default='', verbose_name='Link de Referência')),
                ('organizer', models.CharField(max_length=50, verbose_name='Nome para Contato')),
                ('organizerTel', models.CharField(default='', max_length=20, verbose_name='Telefone para Contato')),
                ('value', models.FloatField(default='0.0', verbose_name='Valor do Ingresso')),
                ('address', models.CharField(max_length=50, verbose_name='Local do Evento')),
                ('linkAddress', models.URLField(default='', verbose_name='Localização no Google Maps')),
                ('eventDate', models.DateField(blank=True, verbose_name='Data do Rolê')),
                ('eventHour', models.TimeField(blank=True, verbose_name='Horário do Rolê')),
                ('adultOnly', models.BooleanField(default=False, verbose_name='+18')),
                ('eventDescription', models.TextField(verbose_name='Descrição')),
                ('photo', models.ImageField(upload_to='', verbose_name='Foto')),
                ('foods', models.TextField(verbose_name='Comidas')),
                ('drinks', models.TextField(verbose_name='Bebidas')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('eventDate', 'eventHour', 'event_name'),
            },
        ),
    ]
