# Generated by Django 2.1.1 on 2018-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=50)),
                ('linkReference', models.URLField(default='')),
                ('organizer', models.CharField(max_length=50)),
                ('organizerTel', models.CharField(default='', max_length=20)),
                ('value', models.FloatField(default='0.0')),
                ('address', models.CharField(max_length=50)),
                ('linkAddress', models.URLField(default='')),
                ('eventDate', models.DateField(blank=True)),
                ('eventHour', models.TimeField(blank=True)),
                ('adultOnly', models.BooleanField(default=True)),
                ('eventDescription', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
                ('foods', models.TextField()),
                ('drinks', models.TextField()),
            ],
        ),
    ]
