# Generated by Django 2.0.5 on 2018-09-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('organizer', models.CharField(max_length=50)),
                ('value', models.FloatField(default='0.0')),
                ('amount', models.IntegerField(default='0')),
                ('address', models.TextField()),
                ('foods', models.TextField()),
                ('drinks', models.TextField()),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
